### ISSUE TITLE
Q: Describe open source in your words

### ISSUE THREAD

**Issue by sboy99** [pbclife/gitopener.vercel.app#26]
Try to explain in a very simple easy to understand (beginner-friendly) words.
This will be referenced in the Application

**Comment by lavanyayangala** [comment]
1.  Open source can be described as for suppose if we are working on project which involves large code and due to human nature we may make mistakes or some errors.
2. We can make it available to public using platforms like Github which promotes collaboration and can find solutions in ease by community collaboration.
3.  So that people can collaborate and rectify the mistakes if found and can be pushed to main branch if it works.
4.  Here collaboration also improves along with chances of profile visibility.
5. In open source collaborations in the form of code and non code play a significant role.
6.  Here we can use open source opportunity using version control systems like Github . @sboy99

**Comment by sboy99** [comment]
Really appreciated, and thank you for for your contribution. would you be able to update the docs? if you can here's some insight you might follow
- create a directory named `general-terminology` inside `docs` directory
- inside `general-terminology` create a file `open-source.mdx`
- add a title in the front-matter section
- in the body add a heading followed by your contribution
- create a pull request,
Thank you again...

**Comment by lavanyayangala** [comment]
Sure i will add it😊

**Comment by lavanyayangala** [comment]
- Added file but something happened please check and please comment here the information.
- Thankyou.
- Thankyou for making me part of the contribution.
- Please check and let me know if any changes are required.
- [(https://github.com/pbclife/gitopener.vercel.app/pull/61)]

**Comment by priyankarpal** [comment]
completed
