### ISSUE TITLE
Bug: 404 error (remove test profiles from the contributors page)

### ISSUE THREAD

**Issue by priyankarpal** [pbclife/gitopener.vercel.app#82]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

After clicking the contributor's profile. It's showing a 404 error. I added a screen recording please check

### Screenshots

https://user-images.githubusercontent.com/88102392/224528921-1dffc2c6-a2de-40cd-a840-472769c24bcf.mp4

### Any additional information?

I'm using Brave Browser

**Comment by Aadarsh805** [comment]
@priyankarpal this is happening because that data doesn't exist in the database right now, those were put there just for testing

trying opening `Sagar Bera`'s profile, that profile exists in the DB and won't show 404
we will be clearing these test profiles soon
Btw you can even add your profile if you want, the docs on how to add haven't been added right now
you can check this open pr https://github.com/pbclife/gitopener.vercel.app/pull/77/files for how to add profile

**Comment by priyankarpal** [comment]
> @priyankarpal this is happening because that data doesn't exist in the database right now, those were put there just for testing
> 
> trying opening `Sagar Bera`'s profile, that profile exists in the DB and won't show 404 we will be clearing these test profiles soon Btw you can even add your profile if you want, the docs on how to add haven't been added right now you can check this open pr https://github.com/pbclife/gitopener.vercel.app/pull/77/files for how to add profile

yeah sure I will add.

**Comment by priyankarpal** [comment]
Added my [Profile](https://github.com/pbclife/gitopener.vercel.app/pull/86/files#diff-bf322d8b7cbb58f86926fca6948740afbbdd3d1924b36e09a3d54568671044f5)

**Comment by sboy99** [comment]
Yup this is solved in v1.0.0
